config/routes.rb
Rails.application.routes.draw do


  root 'homes#top'
  get 'home/about' => 'homes#about'
  resource :home, only: [:top, :about]
  devise_for :users, controllers: { registrations: 'users/registrations',
  									 sessions: 'users/sessions' }

  resources :books, only: [:create, :index, :show, :edit, :update]
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:show, :index, :edit, :update]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, {length: { in: 2..20 }}
  validates :introduction, {length: {maximum: 50}}
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  # GET /resource/sign_up


  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]


  

 
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
       @user = User.find(current_user.id)
  	   @book = Book.new
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
  	@user = User.find(current_user.id)
  	if @user.update(user_params)
  		flash[:notice] = 'You have updated user successfully.'
  		redirect_to user_path(current_user.id)
  	else
  		render :edit
  	end
  end

  def index
  	@book = Book.new
  	@user = User.find(current_user.id)
  	@users = User.all
  end

  def show
  	@book = Book.new
  	@user = User.find(params[:id])
  	@user_books = @user.books
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  	
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user-info.html.erb
<body>
			<div class="col-xs-3">
				<div class="user_info">
						<h2>User info</h2>
						<%= attachment_image_tag @user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
						<table class="table table-striped">
							<tbody>
								<tr>
									<th>name</th>
									<th><%= user.name %></th>
								</tr>
								<tr>
									<th>introduction</th>
									<th><%= user.introduction %></th>
								</tr>
							</tbody>
						</table>
						<div class="row">
								<%= link_to edit_user_path(current_user.id), class: 'col-xs-12 btn btn-default' do %>
								<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
								<% end %>
						</div>

						<h2>New book</h2>
						<%= form_for(book) do |f| %>
							<div class="new-action field row">
								<%= f.label :title, "Title" %>
								<%= f.text_field :title, class: 'col-xs-12'  %>
							</div>
							<div class="new-action field row">
								<%= f.label :body, "Opinion" %>
								<%= f.text_area :body, class: 'col-xs-12'   %>
							</div>
							<div class="submit row" >
								<%= f.submit "Create Book", class: 'new-action col-xs-12 btn create-book' %>
							</div>
						<% end %>
				</div>
			</div>
	
</body>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
	<div class="error_field">
		<h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<body>
	<div class="container">
		<div class="row">
			<div class="col-xs-6 col-xs-offset-3">
				<div class="user-info">
					<h2>User info</h2>
					<%= form_for(@user) do |f| %>
						<div class="field">
							<%= f.label :name, "Name" %>
							<%= f.text_field :name %>
						</div>
						<div class="field">
							<%= f.label :image, "Image" %>
							<%= f.attachment_field :profile_image %>
						</div>
						<div class="field">
							<%= f.label :introduction, "Introduction" %>
							<%= f.text_area :introduction %>
						</div>
						<div class="submit">
							<%= f.submit 'Update User' %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/users/index.html.erb
<body>
	<div class="container">
		<div class="row">
			<h1 class="jquery">Hello jQuery!</h1>
			<%= render 'users/user-info', book: @book , user: @user %>
			<div class="col-xs-9">
				<div class="users_index">
					<h2>Users</h2>
					<table class="table table-striped">
						<thead>
							<th>image</th>
							<th>name</th>
							<th></th>
							<th></th>
						</thead>
						<% @users.each do |user| %>
						<tbody>
							<tr>
								<td><%= attachment_image_tag user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
								<td><%= user.name %></td>
								<td><%= link_to 'Show', user_path(user) %></td>
							</tr>
						</tbody>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/users/show.html.erb
<body>
	<div class="container">
		<div class="row">
			<% if flash[:notice] %>
				<div class="flash">
					<%= flash[:notice] %>
				</div>
			<% end %>
			<%= render 'users/user-info', book: @book , user: @user %>
			<div class="col-xs-9">
				<div class="users_show">
					<h2>Books</h2>
					<table class="table table-striped">
						<thead>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
						</thead>
						<% @user_books.each do |user_book| %>
						<tbody>
							<td><%= link_to attachment_image_tag(@user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "40x40"), user_path(@user) %></td>
							<td><%= link_to user_book.title, book_path(user_book.id) %></td>
							<td><%= user_book.body %></td>
						</tbody>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</div>
</body>
	