config/routes.rb
Rails.application.routes.draw do


  root 'homes#top'
  get 'home/about' => 'homes#about'
  resource :home, only: [:top, :about]
  devise_for :users, controllers: { registrations: 'users/registrations',
  									 sessions: 'users/sessions' }

  resources :books, only: [:create, :index, :show, :edit, :update]
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:show, :index, :edit, :update]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
    validates :body, {presence: true, length: {maximum: 200}}

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def create
		@books = Book.all
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = 'You have creatad book successfully.'
			redirect_to book_path(@book.id)
		else
			@books = Book.all
			@user = User.find(current_user.id)
			render :index
		end
    end

    def index
    	@books = Book.all
    	@book = Book.new
    	@user = User.find(current_user.id)
    end

    def show
    	@book = Book.new
    	@book2 = Book.find(params[:id])
    	@user = User.find_by(id: @book2.user_id)
    end

    def edit
    	@book = Book.find(params[:id])
    	if @book.user_id == current_user.id
    	else
    		redirect_to books_path
    	end
    end

    def update
    	@book = Book.find(params[:id])
    	if @book.update(book_params)
        	flash[:notice] = 'You have updated book successfully.'
        	redirect_to book_path(@book.id)
        else
            render :edit
        end
    end

    def destroy
    	book = Book.find(params[:id])
    	book.destroy
    	redirect_to books_path
    end

    private
    def book_params
    	params.require(:book).permit(:title, :body)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<body>
	<div class="container">
		<div class="row">
			<div class="col-xs-6 col-xs-offset-3">
				<div class="book_edit">
					<h2>Editing Book</h2>
						<% if @book.errors.any? %>
							<div class="error_field">
								<h2 style="color: red;"><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
								<ul>
									<% @book.errors.full_messages.each do |message| %>
										<li style="color: red;"><%= message %></li>
									<% end %>
								</ul>
							</div>
						<% end %>
					<%= form_for(@book) do |f| %>
						<div class="edit-action form row">
							<%= f.label :title, "Title" %>
							<%= f.text_field :title, class: 'col-xs-12' %>
						</div>
						<div class="edit-action form row">
							<%= f.label :body, "Opinion" %>
							<%= f.text_area :body, class: 'col-xs-12'  %>
						</div>
						<div class="submit row">
							<%= f.submit 'Update Book', class: 'edit-action col-xs-12 btn edit-book'  %>
						</div>

						<div>
							<%= link_to "Show", book_path(@book.id) %>
							|
							<%= link_to "Back", books_path %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</body>
	

app/views/books/index.html.erb
<body>
	<div class="container">
		<div class="row">
			<% if @book.errors.any? %>
				<div class="error_field">
					<h2 style="color: red;"><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
					<ul>
						<% @book.errors.full_messages.each do |message| %>
							<li style="color: red;"><%= message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
		</div>
		<div class="row">
			<%= render 'users/user-info', book: @book , user: @user %>
			<div class="col-xs-9">
				<div class="books_index">
					<h2>Books</h2>
					<table class="table table-striped">
						<thead>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th></th>
						</thead>
						<% @books.each do |book| %>
						<tbody>
							<tr>
								<td><%= link_to attachment_image_tag(book.user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "40x40"), user_path(book.user) %></td>
								<td><%= link_to book.title, book_path(book.id) %></td>
								<td><%= book.body %></td>
							</tr>
						</tbody>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</div>
	
</body>

app/views/books/show.html.erb
<body>
	<div class="container">
		<div class="row">
			<% if flash[:notice] %>
				<div class="flash">
					<%= flash[:notice] %>
				</div>
			<% end %>
			<%= render 'users/user-info', book: @book , user: @user %>
			<div class="col-xs-9">
				<div class="book_detail">
					<h2>Book detail</h2>
					<table class="table table-striped">
						<thead>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th></th>
						</thead>
						<tbody>
							<tr>
								<td><%= link_to attachment_image_tag(@user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "40x40"), user_path(@user.id) %><br>
									<%= link_to @user.name, user_path(@user.id) %>
								</td>
								<td>
									<%= link_to @book2.title, book_path(@book2.id) %>
								</td>
								<td><%= @book2.body %></td>
								<% if @book2.user_id == current_user.id %>
									<td>
										<%= link_to edit_book_path(@book2.id) do %>
											<p class="btn editing">Edit</p>
										<% end %>
									</td>
									<td>
										<%= link_to destroy_book_path(@book2.id), method: :delete, data: { confirm: '本当に削除しますか？'} do %>
											<p class="btn destroy">Destroy</p>
										<% end %>
									</td>
								<% end %>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</body>
	