config/routes.rb
Rails.application.routes.draw do


  root 'homes#top'
  get 'home/about' => 'homes#about'
  resource :home, only: [:top, :about]
  devise_for :users, controllers: { registrations: 'users/registrations',
  									 sessions: 'users/sessions' }

  resources :books, only: [:create, :index, :show, :edit, :update]
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:show, :index, :edit, :update]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style="background-color: #000;">
      <div class="container" >
        <nav class="nav navbar-left">
          <span class="top-title">Bookers</span>
        </nav>
        <nav>
        <% if user_signed_in? %>
          <ul class="nav navbar-right">
            <li class="pull-left">
              <%= link_to user_path(current_user.id),  class: "btn" do    %>
                <span class="glyphicon glyphicon-home" aria-hidden="true">  Home</span>
              <% end %>
            </li>
            <li class="pull-left">
              <%= link_to users_path, class: 'btn'  do  %>
                <span class="glyphicon glyphicon-user" aria-hidden="true">  Users</span>
              <% end %>
            </li>
            <li class="pull-left">
              <%= link_to books_path, class: 'btn' do  %>
                <span class="glyphicon glyphicon-book" aria-hidden="true">  Books</span>
              <% end %>
            </li>
            <li class="pull-left">
              <%= link_to destroy_user_session_path, method: :delete, class: 'btn' do  %>
                <span class="glyphicon glyphicon-log-out" aria-hidden="true">  logout</span>
              <% end %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-right">
            <li class="pull-left">
              <%= link_to root_path, class: 'btn' do   %>
                <span class="glyphicon glyphicon-home" aria-hidden="true">  Home</span>
              <% end %>
            </li>
            <li class="pull-left">
              <%= link_to home_about_path, class: 'btn'  do %>
                <span class="glyphicon glyphicon-link about" aria-hidden="true">  About</span>
              <% end %>
            </li>
            <li class="pull-left">
              <%= link_to   new_user_registration_path, class: 'btn'  do %>
                <span class="glyphicon glyphicon-edit" aria-hidden="true">  sign up</span>
              <% end %>
            </li>
            <li class="pull-left">
              <%= link_to new_user_session_path,  class: 'btn' do %>
                <span class="glyphicon glyphicon-log-in" aria-hidden="true">  login</span>
              <% end %>
            </li>
          </ul>
        <% end %>
        </nav>
      </div>
      <div id="container">
        <div id="theTarget">
          <div class="image1"></div>
          <div class="image2"></div>
          <div class="image3"></div>
          <div class="image4"></div>
          <div class="image5"></div>
        </div>
      </div>
    </header>
    <%= yield %>
    <body>
      
    </body>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>